// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"QuestJournal","status":true,"description":"Quest Journal (JSON-backed) - adds a Journal command to the main menu with quest list + details, and plugin commands to start/update/complete quests.","parameters":{}},
{"name":"AltMenuScreen","status":false,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":false,"description":"Alternative save/load screen layout.","parameters":{}}
];
